# Generated by Django 3.0.8 on 2020-07-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislikes',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.CharField(blank=True, default=1, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.CharField(blank=True, default=1, max_length=140, null=True),
        ),
    ]
