# Generated by Django 3.0.8 on 2020-07-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20200715_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.CharField(max_length=40),
        ),
    ]
