# Generated by Django 3.0.8 on 2020-07-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_auto_20200722_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
