# Generated by Django 3.0.8 on 2020-07-27 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_auto_20200722_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['time']},
        ),
    ]
