# Generated by Django 3.0.8 on 2020-07-27 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_auto_20200727_1628'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
