# Generated by Django 3.0.8 on 2020-07-28 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0021_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-time']},
        ),
    ]
